import { components } from "./openapi";

export const POINT_OF_INTEREST_COORDINATES = {
  resource: {
    salmon_fishing_spot: [-3, -4],
    gold_rocks: [6, -3],
    ash_tree: [-1, 0],
    copper_rocks: [2, 0],
    sunflower_field: [2, 2],
    gudgeon_fishing_spot: [4, 2],
    shrimp_fishing_spot: [5, 2],
    birch_tree: [3, 5],
    coal_rocks: [1, 6],
    spruce_tree: [2, 6],
    dead_tree: [9, 6],
    iron_rocks: [1, 7],
    glowstem: [1, 10],
    maple_tree: [1, 12],
    bass_fishing_spot: [6, 12],
    trout_fishing_spot: [7, 12],
    mithril_rocks: [-2, 13],
    nettle: [7, 14],
  },
  monster: {
    bandit_lizard: [-1, -4],
    goblin_wolfrider: [6, -4],
    orc: [7, -4],
    ogre: [8, -4],
    pig: [-3, -3],
    cyclops: [7, -3],
    blue_slime: [0, -2],
    yellow_slime: [1, -2],
    red_slime: [2, -2],
    green_slime: [3, -2],
    goblin: [6, -2],
    corrupted_ogre: [8, -2],
    wolf: [-3, 0],
    chicken: [0, 1],
    owlbear: [10, 1],
    cow: [0, 2],
    mushmush: [5, 3],
    flying_snake: [5, 4],
    skeleton: [8, 6],
    vampire: [10, 6],
    demon: [-3, 7],
    death_knight: [8, 7],
    lich: [9, 7],
    bat: [11, 7],
    highwayman: [2, 8],
    cursed_tree: [9, 9],
    spider: [-3, 12],
    imp: [0, 12],
    sheep: [5, 12],
    hellhound: [-1, 13],
    cultist_acolyte: [1, 13],
  },
  workshop: {
    woodcutting: [-2, -3],
    cooking: [1, 1],
    weaponcrafting: [2, 1],
    gearcrafting: [3, 1],
    jewelrycrafting: [1, 3],
    alchemy: [2, 3],
    mining: [1, 5],
  },
  bank: { bank: [4, 1] },
  grand_exchange: { grand_exchange: [5, 1] },
  tasks_master: { monsters: [1, 2], items: [4, 13] },
  npc: {
    tailor: [3, 3],
    tasks_trader: [5, 11],
    cultist_wizard: [2, 13],
    archaeologist: [6, 13],
    rune_vendor: [8, 13],
  },
};

export const ALL_NPC_TRADES = [
  {
    code: "algae",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 50,
    sell_price: 1,
  },
  {
    code: "ash_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 10,
    sell_price: 1,
  },
  {
    code: "astralyte_crystal",
    npc: "tasks_trader",
    currency: "tasks_coin",
    buy_price: 12,
    sell_price: null,
  },
  {
    code: "backpack",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: 50000,
    sell_price: null,
  },
  {
    code: "bag_of_gold",
    npc: "cultist_wizard",
    currency: "corrupted_gem",
    buy_price: 8,
    sell_price: null,
  },
  {
    code: "bandit_armor",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 5000,
  },
  {
    code: "bass",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 50,
    sell_price: 1,
  },
  {
    code: "birch_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 35,
    sell_price: 1,
  },
  {
    code: "book_from_hell",
    npc: "archaeologist",
    currency: "page_from_hell",
    buy_price: 24,
    sell_price: null,
  },
  {
    code: "burn_rune",
    npc: "rune_vendor",
    currency: "gold",
    buy_price: 25000,
    sell_price: null,
  },
  {
    code: "cloth",
    npc: "tailor",
    currency: "wool",
    buy_price: 3,
    sell_price: null,
  },
  {
    code: "coal",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 35,
    sell_price: 1,
  },
  {
    code: "copper_ore",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 10,
    sell_price: 1,
  },
  {
    code: "corrupted_crown",
    npc: "cultist_wizard",
    currency: "corrupted_gem",
    buy_price: 220,
    sell_price: null,
  },
  {
    code: "corrupted_fruit",
    npc: "cultist_wizard",
    currency: "corrupted_gem",
    buy_price: 1,
    sell_price: null,
  },
  {
    code: "corrupted_skull",
    npc: "cultist_wizard",
    currency: "corrupted_gem",
    buy_price: 75,
    sell_price: null,
  },
  {
    code: "cursed_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 350,
    sell_price: 35,
  },
  {
    code: "dead_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 50,
    sell_price: 1,
  },
  {
    code: "death_knight_sword",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 5000,
  },
  {
    code: "diabolic_elixir",
    npc: "cultist_wizard",
    currency: "corrupted_gem",
    buy_price: 2,
    sell_price: null,
  },
  {
    code: "diamond",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 40000,
    sell_price: 10000,
  },
  {
    code: "emerald",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 6000,
    sell_price: 1500,
  },
  {
    code: "emerald_book",
    npc: "archaeologist",
    currency: "elemental_page",
    buy_price: 30,
    sell_price: null,
  },
  {
    code: "enchanted_fabric",
    npc: "tasks_trader",
    currency: "tasks_coin",
    buy_price: 14,
    sell_price: null,
  },
  {
    code: "forest_ring",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 200,
  },
  {
    code: "frozen_axe",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 200000,
    sell_price: null,
  },
  {
    code: "frozen_fishing_rod",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 200000,
    sell_price: null,
  },
  {
    code: "frozen_gloves",
    npc: "herbal_merchant",
    currency: "gold",
    buy_price: 200000,
    sell_price: null,
  },
  {
    code: "frozen_pickaxe",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 200000,
    sell_price: null,
  },
  {
    code: "glowstem_leaf",
    npc: "herbal_merchant",
    currency: "gold",
    buy_price: 75,
    sell_price: 1,
  },
  {
    code: "gold_ore",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 50,
    sell_price: 1,
  },
  {
    code: "golden_egg",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 2000,
  },
  {
    code: "golden_shrimp",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 1000,
  },
  {
    code: "gudgeon",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 10,
    sell_price: 1,
  },
  {
    code: "hard_leather",
    npc: "tailor",
    currency: "cowhide",
    buy_price: 3,
    sell_price: null,
  },
  {
    code: "healing_rune",
    npc: "rune_vendor",
    currency: "gold",
    buy_price: 20000,
    sell_price: null,
  },
  {
    code: "highwayman_dagger",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 500,
  },
  {
    code: "iron_ore",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 25,
    sell_price: 1,
  },
  {
    code: "jasper_crystal",
    npc: "tasks_trader",
    currency: "tasks_coin",
    buy_price: 8,
    sell_price: null,
  },
  {
    code: "lich_crown",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 10000,
  },
  {
    code: "life_crystal",
    npc: "archaeologist",
    currency: "life_crystal_shard",
    buy_price: 24,
    sell_price: null,
  },
  {
    code: "lifesteal_rune",
    npc: "rune_vendor",
    currency: "gold",
    buy_price: 30000,
    sell_price: null,
  },
  {
    code: "lost_world_map",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: 10000,
    sell_price: null,
  },
  {
    code: "magic_sap",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 1500,
    sell_price: 150,
  },
  {
    code: "magic_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 100,
    sell_price: 1,
  },
  {
    code: "magical_cure",
    npc: "tasks_trader",
    currency: "tasks_coin",
    buy_price: 8,
    sell_price: null,
  },
  {
    code: "malefic_crystal",
    npc: "archaeologist",
    currency: "malefic_shard",
    buy_price: 24,
    sell_price: null,
  },
  {
    code: "maple_sap",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 500,
    sell_price: 50,
  },
  {
    code: "maple_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 75,
    sell_price: 1,
  },
  {
    code: "minor_health_potion",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: 600,
    sell_price: 20,
  },
  {
    code: "mithril_ore",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 75,
    sell_price: 1,
  },
  {
    code: "nettle_leaf",
    npc: "herbal_merchant",
    currency: "gold",
    buy_price: 35,
    sell_price: 1,
  },
  {
    code: "old_boots",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 800,
  },
  {
    code: "perfect_pearl",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 5000,
  },
  {
    code: "perfect_pearl",
    npc: "archaeologist",
    currency: "small_pearls",
    buy_price: 20,
    sell_price: null,
  },
  {
    code: "piece_of_obsidian",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 350,
    sell_price: 35,
  },
  {
    code: "recall_potion",
    npc: "herbal_merchant",
    currency: "gold",
    buy_price: 50,
    sell_price: null,
  },
  {
    code: "ruby",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 6000,
    sell_price: 1500,
  },
  {
    code: "ruby_book",
    npc: "archaeologist",
    currency: "elemental_page",
    buy_price: 30,
    sell_price: null,
  },
  {
    code: "salmon",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 75,
    sell_price: 1,
  },
  {
    code: "sap",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 300,
    sell_price: 30,
  },
  {
    code: "sapphire",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 6000,
    sell_price: 1500,
  },
  {
    code: "sapphire_book",
    npc: "archaeologist",
    currency: "elemental_page",
    buy_price: 30,
    sell_price: null,
  },
  {
    code: "shell",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 120,
  },
  {
    code: "shrimp",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 25,
    sell_price: 1,
  },
  {
    code: "small_antidote",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: 800,
    sell_price: 25,
  },
  {
    code: "snakeskin",
    npc: "tailor",
    currency: "snake_hide",
    buy_price: 4,
    sell_price: null,
  },
  {
    code: "south_bank_potion",
    npc: "herbal_merchant",
    currency: "gold",
    buy_price: 50,
    sell_price: null,
  },
  {
    code: "spruce_wood",
    npc: "timber_merchant",
    currency: "gold",
    buy_price: 25,
    sell_price: 1,
  },
  {
    code: "strange_ore",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 100,
    sell_price: 1,
  },
  {
    code: "sunflower",
    npc: "herbal_merchant",
    currency: "gold",
    buy_price: 10,
    sell_price: 1,
  },
  {
    code: "topaz",
    npc: "gemstone_merchant",
    currency: "gold",
    buy_price: 6000,
    sell_price: 1500,
  },
  {
    code: "topaz_book",
    npc: "archaeologist",
    currency: "elemental_page",
    buy_price: 30,
    sell_price: null,
  },
  {
    code: "trout",
    npc: "fish_merchant",
    currency: "gold",
    buy_price: 35,
    sell_price: 1,
  },
  {
    code: "wolf_ears",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 500,
  },
  {
    code: "wooden_club",
    npc: "nomadic_merchant",
    currency: "gold",
    buy_price: null,
    sell_price: 600,
  },
] as const;

export const SEGMENTED_NPC_TRADES = {
  fish_merchant: [
    {
      code: "algae",
      currency: "gold",
      buy_price: 50,
      sell_price: 1,
    },
    {
      code: "bass",
      currency: "gold",
      buy_price: 50,
      sell_price: 1,
    },
    {
      code: "frozen_fishing_rod",
      currency: "gold",
      buy_price: 200000,
      sell_price: null,
    },
    {
      code: "golden_shrimp",
      currency: "gold",
      buy_price: null,
      sell_price: 1000,
    },
    {
      code: "gudgeon",
      currency: "gold",
      buy_price: 10,
      sell_price: 1,
    },
    {
      code: "perfect_pearl",
      currency: "gold",
      buy_price: null,
      sell_price: 5000,
    },
    {
      code: "salmon",
      currency: "gold",
      buy_price: 75,
      sell_price: 1,
    },
    {
      code: "shell",
      currency: "gold",
      buy_price: null,
      sell_price: 120,
    },
    {
      code: "shrimp",
      currency: "gold",
      buy_price: 25,
      sell_price: 1,
    },
    {
      code: "trout",
      currency: "gold",
      buy_price: 35,
      sell_price: 1,
    },
  ],
  timber_merchant: [
    {
      code: "ash_wood",
      currency: "gold",
      buy_price: 10,
      sell_price: 1,
    },
    {
      code: "birch_wood",
      currency: "gold",
      buy_price: 35,
      sell_price: 1,
    },
    {
      code: "cursed_wood",
      currency: "gold",
      buy_price: 350,
      sell_price: 35,
    },
    {
      code: "dead_wood",
      currency: "gold",
      buy_price: 50,
      sell_price: 1,
    },
    {
      code: "frozen_axe",
      currency: "gold",
      buy_price: 200000,
      sell_price: null,
    },
    {
      code: "magic_sap",
      currency: "gold",
      buy_price: 1500,
      sell_price: 150,
    },
    {
      code: "magic_wood",
      currency: "gold",
      buy_price: 100,
      sell_price: 1,
    },
    {
      code: "maple_sap",
      currency: "gold",
      buy_price: 500,
      sell_price: 50,
    },
    {
      code: "maple_wood",
      currency: "gold",
      buy_price: 75,
      sell_price: 1,
    },
    {
      code: "sap",
      currency: "gold",
      buy_price: 300,
      sell_price: 30,
    },
    {
      code: "spruce_wood",
      currency: "gold",
      buy_price: 25,
      sell_price: 1,
    },
  ],
  tasks_trader: [
    {
      code: "astralyte_crystal",
      currency: "tasks_coin",
      buy_price: 12,
      sell_price: null,
    },
    {
      code: "enchanted_fabric",
      currency: "tasks_coin",
      buy_price: 14,
      sell_price: null,
    },
    {
      code: "jasper_crystal",
      currency: "tasks_coin",
      buy_price: 8,
      sell_price: null,
    },
    {
      code: "magical_cure",
      currency: "tasks_coin",
      buy_price: 8,
      sell_price: null,
    },
  ],
  nomadic_merchant: [
    {
      code: "backpack",
      currency: "gold",
      buy_price: 50000,
      sell_price: null,
    },
    {
      code: "bandit_armor",
      currency: "gold",
      buy_price: null,
      sell_price: 5000,
    },
    {
      code: "death_knight_sword",
      currency: "gold",
      buy_price: null,
      sell_price: 5000,
    },
    {
      code: "forest_ring",
      currency: "gold",
      buy_price: null,
      sell_price: 200,
    },
    {
      code: "golden_egg",
      currency: "gold",
      buy_price: null,
      sell_price: 2000,
    },
    {
      code: "highwayman_dagger",
      currency: "gold",
      buy_price: null,
      sell_price: 500,
    },
    {
      code: "lich_crown",
      currency: "gold",
      buy_price: null,
      sell_price: 10000,
    },
    {
      code: "lost_world_map",
      currency: "gold",
      buy_price: 10000,
      sell_price: null,
    },
    {
      code: "minor_health_potion",
      currency: "gold",
      buy_price: 600,
      sell_price: 20,
    },
    {
      code: "old_boots",
      currency: "gold",
      buy_price: null,
      sell_price: 800,
    },
    {
      code: "small_antidote",
      currency: "gold",
      buy_price: 800,
      sell_price: 25,
    },
    {
      code: "wolf_ears",
      currency: "gold",
      buy_price: null,
      sell_price: 500,
    },
    {
      code: "wooden_club",
      currency: "gold",
      buy_price: null,
      sell_price: 600,
    },
  ],
  cultist_wizard: [
    {
      code: "bag_of_gold",
      currency: "corrupted_gem",
      buy_price: 8,
      sell_price: null,
    },
    {
      code: "corrupted_crown",
      currency: "corrupted_gem",
      buy_price: 220,
      sell_price: null,
    },
    {
      code: "corrupted_fruit",
      currency: "corrupted_gem",
      buy_price: 1,
      sell_price: null,
    },
    {
      code: "corrupted_skull",
      currency: "corrupted_gem",
      buy_price: 75,
      sell_price: null,
    },
    {
      code: "diabolic_elixir",
      currency: "corrupted_gem",
      buy_price: 2,
      sell_price: null,
    },
  ],
  archaeologist: [
    {
      code: "book_from_hell",
      currency: "page_from_hell",
      buy_price: 24,
      sell_price: null,
    },
    {
      code: "emerald_book",
      currency: "elemental_page",
      buy_price: 30,
      sell_price: null,
    },
    {
      code: "life_crystal",
      currency: "life_crystal_shard",
      buy_price: 24,
      sell_price: null,
    },
    {
      code: "malefic_crystal",
      currency: "malefic_shard",
      buy_price: 24,
      sell_price: null,
    },
    {
      code: "perfect_pearl",
      currency: "small_pearls",
      buy_price: 20,
      sell_price: null,
    },
    {
      code: "ruby_book",
      currency: "elemental_page",
      buy_price: 30,
      sell_price: null,
    },
    {
      code: "sapphire_book",
      currency: "elemental_page",
      buy_price: 30,
      sell_price: null,
    },
    {
      code: "topaz_book",
      currency: "elemental_page",
      buy_price: 30,
      sell_price: null,
    },
  ],
  rune_vendor: [
    {
      code: "burn_rune",
      currency: "gold",
      buy_price: 25000,
      sell_price: null,
    },
    {
      code: "healing_rune",
      currency: "gold",
      buy_price: 20000,
      sell_price: null,
    },
    {
      code: "lifesteal_rune",
      currency: "gold",
      buy_price: 30000,
      sell_price: null,
    },
  ],
  tailor: [
    {
      code: "cloth",
      currency: "wool",
      buy_price: 3,
      sell_price: null,
    },
    {
      code: "hard_leather",
      currency: "cowhide",
      buy_price: 3,
      sell_price: null,
    },
    {
      code: "snakeskin",
      currency: "snake_hide",
      buy_price: 4,
      sell_price: null,
    },
  ],
  gemstone_merchant: [
    {
      code: "coal",
      currency: "gold",
      buy_price: 35,
      sell_price: 1,
    },
    {
      code: "copper_ore",
      currency: "gold",
      buy_price: 10,
      sell_price: 1,
    },
    {
      code: "diamond",
      currency: "gold",
      buy_price: 40000,
      sell_price: 10000,
    },
    {
      code: "emerald",
      currency: "gold",
      buy_price: 6000,
      sell_price: 1500,
    },
    {
      code: "frozen_pickaxe",
      currency: "gold",
      buy_price: 200000,
      sell_price: null,
    },
    {
      code: "gold_ore",
      currency: "gold",
      buy_price: 50,
      sell_price: 1,
    },
    {
      code: "iron_ore",
      currency: "gold",
      buy_price: 25,
      sell_price: 1,
    },
    {
      code: "mithril_ore",
      currency: "gold",
      buy_price: 75,
      sell_price: 1,
    },
    {
      code: "piece_of_obsidian",
      currency: "gold",
      buy_price: 350,
      sell_price: 35,
    },
    {
      code: "ruby",
      currency: "gold",
      buy_price: 6000,
      sell_price: 1500,
    },
    {
      code: "sapphire",
      currency: "gold",
      buy_price: 6000,
      sell_price: 1500,
    },
    {
      code: "strange_ore",
      currency: "gold",
      buy_price: 100,
      sell_price: 1,
    },
    {
      code: "topaz",
      currency: "gold",
      buy_price: 6000,
      sell_price: 1500,
    },
  ],
  herbal_merchant: [
    {
      code: "frozen_gloves",
      currency: "gold",
      buy_price: 200000,
      sell_price: null,
    },
    {
      code: "glowstem_leaf",
      currency: "gold",
      buy_price: 75,
      sell_price: 1,
    },
    {
      code: "nettle_leaf",
      currency: "gold",
      buy_price: 35,
      sell_price: 1,
    },
    {
      code: "recall_potion",
      currency: "gold",
      buy_price: 50,
      sell_price: null,
    },
    {
      code: "south_bank_potion",
      currency: "gold",
      buy_price: 50,
      sell_price: null,
    },
    {
      code: "sunflower",
      currency: "gold",
      buy_price: 10,
      sell_price: 1,
    },
  ],
} as const;

export const MAP: components["schemas"]["MapSchema"][] = [
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -3,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 1,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 2,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 3,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 4,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 5,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 6,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 7,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 8,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 9,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: -5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_lake1",
    x: -3,
    y: -4,
    content: {
      type: "resource",
      code: "salmon_fishing_spot",
    },
  },
  {
    name: "Forest",
    skin: "forest_lake2",
    x: -2,
    y: -4,
    content: {
      type: "resource",
      code: "salmon_fishing_spot",
    },
  },
  {
    name: "Forest",
    skin: "forest_event_lizard1",
    x: -1,
    y: -4,
    content: {
      type: "monster",
      code: "bandit_lizard",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 0,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 1,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 2,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_goblin_wolfrider1",
    x: 6,
    y: -4,
    content: {
      type: "monster",
      code: "goblin_wolfrider",
    },
  },
  {
    name: "Forest",
    skin: "forest_orc2",
    x: 7,
    y: -4,
    content: {
      type: "monster",
      code: "orc",
    },
  },
  {
    name: "Forest",
    skin: "forest_ogre1",
    x: 8,
    y: -4,
    content: {
      type: "monster",
      code: "ogre",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 9,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 10,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 11,
    y: -4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_pig1",
    x: -3,
    y: -3,
    content: {
      type: "monster",
      code: "pig",
    },
  },
  {
    name: "Forest",
    skin: "forest_woodcuttingstation1",
    x: -2,
    y: -3,
    content: {
      type: "workshop",
      code: "woodcutting",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 1,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 2,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 3,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 4,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 5,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_goldore1",
    x: 6,
    y: -3,
    content: {
      type: "resource",
      code: "gold_rocks",
    },
  },
  {
    name: "Forest",
    skin: "forest_cyclops2",
    x: 7,
    y: -3,
    content: {
      type: "monster",
      code: "cyclops",
    },
  },
  {
    name: "Forest",
    skin: "forest_cyclops1",
    x: 8,
    y: -3,
    content: {
      type: "monster",
      code: "cyclops",
    },
  },
  {
    name: "Forest",
    skin: "forest_goblin_wolfrider2",
    x: 9,
    y: -3,
    content: {
      type: "monster",
      code: "goblin_wolfrider",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: -3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -2,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -1,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_blueslime1",
    x: 0,
    y: -2,
    content: {
      type: "monster",
      code: "blue_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_yellowslime1",
    x: 1,
    y: -2,
    content: {
      type: "monster",
      code: "yellow_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_redslime2",
    x: 2,
    y: -2,
    content: {
      type: "monster",
      code: "red_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_greenslime1",
    x: 3,
    y: -2,
    content: {
      type: "monster",
      code: "green_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_goblin1",
    x: 6,
    y: -2,
    content: {
      type: "monster",
      code: "goblin",
    },
  },
  {
    name: "Forest",
    skin: "forest_orc1",
    x: 7,
    y: -2,
    content: {
      type: "monster",
      code: "orc",
    },
  },
  {
    name: "Forest",
    skin: "forest_corruptedogre2",
    x: 8,
    y: -2,
    content: {
      type: "monster",
      code: "corrupted_ogre",
    },
  },
  {
    name: "Forest",
    skin: "forest_goblin2",
    x: 9,
    y: -2,
    content: {
      type: "monster",
      code: "goblin",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 10,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 11,
    y: -2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -4,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -2,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -1,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_greenslime2",
    x: 0,
    y: -1,
    content: {
      type: "monster",
      code: "green_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_redslime1",
    x: 1,
    y: -1,
    content: {
      type: "monster",
      code: "red_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_blueslime2",
    x: 2,
    y: -1,
    content: {
      type: "monster",
      code: "blue_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 3,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_yellowslime2",
    x: 4,
    y: -1,
    content: {
      type: "monster",
      code: "yellow_slime",
    },
  },
  {
    name: "Forest",
    skin: "forest_road12",
    x: 5,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_road13",
    x: 6,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_road14",
    x: 7,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_road15",
    x: 8,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 9,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 10,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 11,
    y: -1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -5,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -4,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_wolf2",
    x: -3,
    y: 0,
    content: {
      type: "monster",
      code: "wolf",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_ashtree2",
    x: -1,
    y: 0,
    content: {
      type: "resource",
      code: "ash_tree",
    },
  },
  {
    name: "Spawn",
    skin: "spawn",
    x: 0,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 1,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_copperore1",
    x: 2,
    y: 0,
    content: {
      type: "resource",
      code: "copper_rocks",
    },
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 3,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 4,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_road11",
    x: 5,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 6,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 8,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 9,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 11,
    y: 0,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -4,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_wolf1",
    x: -2,
    y: 1,
    content: {
      type: "monster",
      code: "wolf",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: 1,
    content: null,
  },
  {
    name: "City",
    skin: "forest_chicken1",
    x: 0,
    y: 1,
    content: {
      type: "monster",
      code: "chicken",
    },
  },
  {
    name: "City",
    skin: "forest_cs1",
    x: 1,
    y: 1,
    content: {
      type: "workshop",
      code: "cooking",
    },
  },
  {
    name: "City",
    skin: "forest_wcstation1",
    x: 2,
    y: 1,
    content: {
      type: "workshop",
      code: "weaponcrafting",
    },
  },
  {
    name: "City",
    skin: "forest_gcstation1",
    x: 3,
    y: 1,
    content: {
      type: "workshop",
      code: "gearcrafting",
    },
  },
  {
    name: "City",
    skin: "forest_bank1",
    x: 4,
    y: 1,
    content: {
      type: "bank",
      code: "bank",
    },
  },
  {
    name: "City",
    skin: "forest_grand_exchange1",
    x: 5,
    y: 1,
    content: {
      type: "grand_exchange",
      code: "grand_exchange",
    },
  },
  {
    name: "Forest",
    skin: "forest_ashtree1",
    x: 6,
    y: 1,
    content: {
      type: "resource",
      code: "ash_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 8,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 9,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_owlbear1",
    x: 10,
    y: 1,
    content: {
      type: "monster",
      code: "owlbear",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 1,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -5,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -4,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -3,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -1,
    y: 2,
    content: null,
  },
  {
    name: "City",
    skin: "forest_cow1",
    x: 0,
    y: 2,
    content: {
      type: "monster",
      code: "cow",
    },
  },
  {
    name: "City",
    skin: "forest_village3",
    x: 1,
    y: 2,
    content: {
      type: "tasks_master",
      code: "monsters",
    },
  },
  {
    name: "City",
    skin: "forest_village1",
    x: 2,
    y: 2,
    content: {
      type: "resource",
      code: "sunflower_field",
    },
  },
  {
    name: "City",
    skin: "forest_village2",
    x: 3,
    y: 2,
    content: null,
  },
  {
    name: "Lake",
    skin: "forest_lake3",
    x: 4,
    y: 2,
    content: {
      type: "resource",
      code: "gudgeon_fishing_spot",
    },
  },
  {
    name: "Lake",
    skin: "forest_lake4",
    x: 5,
    y: 2,
    content: {
      type: "resource",
      code: "shrimp_fishing_spot",
    },
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 6,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 7,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 8,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 9,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_owlbear2",
    x: 10,
    y: 2,
    content: {
      type: "monster",
      code: "owlbear",
    },
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 11,
    y: 2,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -3,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -2,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -1,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: 3,
    content: null,
  },
  {
    name: "City",
    skin: "forest_jewelrycrafting1",
    x: 1,
    y: 3,
    content: {
      type: "workshop",
      code: "jewelrycrafting",
    },
  },
  {
    name: "City",
    skin: "forest_alchemy1",
    x: 2,
    y: 3,
    content: {
      type: "workshop",
      code: "alchemy",
    },
  },
  {
    name: "City",
    skin: "forest_tailor1",
    x: 3,
    y: 3,
    content: {
      type: "npc",
      code: "tailor",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_mushmush1",
    x: 5,
    y: 3,
    content: {
      type: "monster",
      code: "mushmush",
    },
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 6,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 7,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 8,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 9,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 10,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 11,
    y: 3,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -2,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 0,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 1,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_village5",
    x: 2,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_flyingserpent1",
    x: 5,
    y: 4,
    content: {
      type: "monster",
      code: "flying_snake",
    },
  },
  {
    name: "Forest",
    skin: "forest_mushmush2",
    x: 6,
    y: 4,
    content: {
      type: "monster",
      code: "mushmush",
    },
  },
  {
    name: "Forest",
    skin: "forest_flyingserpent2",
    x: 7,
    y: 4,
    content: {
      type: "monster",
      code: "flying_snake",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 8,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 9,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 11,
    y: 4,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -4,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -3,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -2,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -1,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: 5,
    content: null,
  },
  {
    name: "Forest (Forge)",
    skin: "forest_miningstation1",
    x: 1,
    y: 5,
    content: {
      type: "workshop",
      code: "mining",
    },
  },
  {
    name: "Forest",
    skin: "forest_village6",
    x: 2,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_birchtree2",
    x: 3,
    y: 5,
    content: {
      type: "resource",
      code: "birch_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 6,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 7,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 8,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 9,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 10,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 5,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -5,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -4,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -3,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_birchtree1",
    x: -1,
    y: 6,
    content: {
      type: "resource",
      code: "birch_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_coal1",
    x: 1,
    y: 6,
    content: {
      type: "resource",
      code: "coal_rocks",
    },
  },
  {
    name: "Forest",
    skin: "forest_sprucetree2",
    x: 2,
    y: 6,
    content: {
      type: "resource",
      code: "spruce_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 5,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 6,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 6,
    content: null,
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton1",
    x: 8,
    y: 6,
    content: {
      type: "monster",
      code: "skeleton",
    },
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton2",
    x: 9,
    y: 6,
    content: {
      type: "resource",
      code: "dead_tree",
    },
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton3",
    x: 10,
    y: 6,
    content: {
      type: "monster",
      code: "vampire",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 6,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -4,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_portal",
    x: -3,
    y: 7,
    content: {
      type: "monster",
      code: "demon",
    },
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -2,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_ironore2",
    x: 1,
    y: 7,
    content: {
      type: "resource",
      code: "iron_rocks",
    },
  },
  {
    name: "Forest",
    skin: "forest_road1",
    x: 2,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 6,
    y: 7,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 7,
    content: null,
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton4",
    x: 8,
    y: 7,
    content: {
      type: "monster",
      code: "death_knight",
    },
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton5",
    x: 9,
    y: 7,
    content: {
      type: "monster",
      code: "lich",
    },
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton6",
    x: 10,
    y: 7,
    content: {
      type: "monster",
      code: "death_knight",
    },
  },
  {
    name: "Forest",
    skin: "forest_bat2",
    x: 11,
    y: 7,
    content: {
      type: "monster",
      code: "bat",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -5,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -4,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -3,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -2,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -1,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 1,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_highwayman1",
    x: 2,
    y: 8,
    content: {
      type: "monster",
      code: "highwayman",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 3,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 6,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 8,
    content: null,
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton7",
    x: 8,
    y: 8,
    content: {
      type: "monster",
      code: "skeleton",
    },
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton8",
    x: 9,
    y: 8,
    content: {
      type: "resource",
      code: "dead_tree",
    },
  },
  {
    name: "Graveyard",
    skin: "forest_skeleton9",
    x: 10,
    y: 8,
    content: {
      type: "monster",
      code: "vampire",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 8,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -5,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -4,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -3,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -2,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 0,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_sprucetree1",
    x: 1,
    y: 9,
    content: {
      type: "resource",
      code: "spruce_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_road3",
    x: 2,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 6,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_bat1",
    x: 8,
    y: 9,
    content: {
      type: "monster",
      code: "bat",
    },
  },
  {
    name: "Forest",
    skin: "forest_cursed_tree1",
    x: 9,
    y: 9,
    content: {
      type: "monster",
      code: "cursed_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 9,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -4,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -2,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -1,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 0,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_glowstem1",
    x: 1,
    y: 10,
    content: {
      type: "resource",
      code: "glowstem",
    },
  },
  {
    name: "Forest",
    skin: "forest_road7",
    x: 2,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 3,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 4,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 5,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 6,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 7,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 8,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 9,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 10,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -4,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 0,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 1,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_road3",
    x: 2,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 3,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 4,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_taskstrader1",
    x: 5,
    y: 11,
    content: {
      type: "npc",
      code: "tasks_trader",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 6,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 8,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 9,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 10,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 11,
    y: 11,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -5,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -4,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_spider1",
    x: -3,
    y: 12,
    content: {
      type: "monster",
      code: "spider",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_cultis1",
    x: -1,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_imp1",
    x: 0,
    y: 12,
    content: {
      type: "monster",
      code: "imp",
    },
  },
  {
    name: "Forest",
    skin: "forest_mapletree1",
    x: 1,
    y: 12,
    content: {
      type: "resource",
      code: "maple_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_road3",
    x: 2,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 3,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 4,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_sheep1",
    x: 5,
    y: 12,
    content: {
      type: "monster",
      code: "sheep",
    },
  },
  {
    name: "Lake",
    skin: "forest_lake1",
    x: 6,
    y: 12,
    content: {
      type: "resource",
      code: "bass_fishing_spot",
    },
  },
  {
    name: "Lake",
    skin: "forest_lake2",
    x: 7,
    y: 12,
    content: {
      type: "resource",
      code: "trout_fishing_spot",
    },
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 8,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 9,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 10,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 11,
    y: 12,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -5,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -4,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_mithrilore1",
    x: -2,
    y: 13,
    content: {
      type: "resource",
      code: "mithril_rocks",
    },
  },
  {
    name: "Forest",
    skin: "forest_hellhound2",
    x: -1,
    y: 13,
    content: {
      type: "monster",
      code: "hellhound",
    },
  },
  {
    name: "Forest",
    skin: "forest_house1",
    x: 0,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_cultistacolyte1",
    x: 1,
    y: 13,
    content: {
      type: "monster",
      code: "cultist_acolyte",
    },
  },
  {
    name: "Forest",
    skin: "forest_road4_cultistwizard",
    x: 2,
    y: 13,
    content: {
      type: "npc",
      code: "cultist_wizard",
    },
  },
  {
    name: "Forest",
    skin: "forest_road6",
    x: 3,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_road10",
    x: 4,
    y: 13,
    content: {
      type: "tasks_master",
      code: "items",
    },
  },
  {
    name: "Forest",
    skin: "forest_road9",
    x: 5,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_archaeologist1",
    x: 6,
    y: 13,
    content: {
      type: "npc",
      code: "archaeologist",
    },
  },
  {
    name: "Forest",
    skin: "forest_bank2",
    x: 7,
    y: 13,
    content: {
      type: "bank",
      code: "bank",
    },
  },
  {
    name: "Forest",
    skin: "forest_runevendor1",
    x: 8,
    y: 13,
    content: {
      type: "npc",
      code: "rune_vendor",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 9,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 10,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 11,
    y: 13,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -5,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -4,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: -3,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: -2,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_cultistacolyte2",
    x: -1,
    y: 14,
    content: {
      type: "monster",
      code: "cultist_acolyte",
    },
  },
  {
    name: "Forest",
    skin: "forest_imp2",
    x: 0,
    y: 14,
    content: {
      type: "monster",
      code: "imp",
    },
  },
  {
    name: "Forest",
    skin: "forest_hellhound1",
    x: 1,
    y: 14,
    content: {
      type: "monster",
      code: "hellhound",
    },
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 2,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_mapletree2",
    x: 4,
    y: 14,
    content: {
      type: "resource",
      code: "maple_tree",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 5,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 6,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_nettle1",
    x: 7,
    y: 14,
    content: {
      type: "resource",
      code: "nettle",
    },
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 8,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 9,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 10,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 11,
    y: 14,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -5,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -4,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -3,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: -2,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: -1,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 0,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 1,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 2,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 3,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_1",
    x: 4,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_4",
    x: 5,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 6,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 7,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 8,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_2",
    x: 9,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 10,
    y: 15,
    content: null,
  },
  {
    name: "Forest",
    skin: "forest_3",
    x: 11,
    y: 15,
    content: null,
  },
] as const;
